### ISSUE TITLE
Race conditions, racy tests and failures with -race

### ISSUE THREAD

**Issue by zikaeroh** [leononame/clock#1]
I've been having some trouble getting tickers to work consistently in my project, and when running the race detector during my tests, I found that some of the raciness was actually coming from here. If I go and run the tests in this repo, some of them fail, and others show race conditions. Here's an output I got:

<details>
<summary>Output</summary>

==================
WARNING: DATA RACE
Read at 0x00c000016118 by goroutine 9:
  github.com/leononame/clock.TestMock_RunUntilDone()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_fake_test.go:38 +0x20d
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163

Previous write at 0x00c000016118 by goroutine 10:
  sync/atomic.AddInt32()
      /usr/lib/go/src/runtime/race_amd64.s:269 +0xb
  github.com/leononame/clock.incUponReceive()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/ticker_test.go:14 +0x57

Goroutine 9 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:138 +0x334

Goroutine 10 (running) created at:
  github.com/leononame/clock.TestMock_RunUntilDone()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_fake_test.go:31 +0xc7
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163
==================
--- FAIL: TestMock_RunUntilDone (0.10s)
    testing.go:809: race detected during execution of test
--- FAIL: TestMock_After (0.00s)
    clock_fake_test.go:69: 
        	Error Trace:	clock_fake_test.go:69
        	Error:      	Should not be zero, but was 0
        	Test:       	TestMock_After
==================
WARNING: DATA RACE
Read at 0x00c000144298 by goroutine 18:
  github.com/leononame/clock.(*fakeTimer).Execute()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/timer.go:177 +0xc7
  github.com/leononame/clock.(*Mock).tickNext()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock.go:166 +0x1e1
  github.com/leononame/clock.(*Mock).tick()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock.go:148 +0x8c
  github.com/leononame/clock.(*Mock).Forward()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock.go:116 +0x137
  github.com/leononame/clock.TestMock_Sleep()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_fake_test.go:98 +0x125
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163

Previous write at 0x00c000144298 by goroutine 19:
  github.com/leononame/clock.(*Mock).NewTimer()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock.go:219 +0xa4
  github.com/leononame/clock.(*Mock).After()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock.go:179 +0x5e
  github.com/leononame/clock.(*Mock).Sleep()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock.go:200 +0x5a
  github.com/leononame/clock.TestMock_Sleep.func1()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_fake_test.go:91 +0x47

Goroutine 18 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:138 +0x334

Goroutine 19 (running) created at:
  github.com/leononame/clock.TestMock_Sleep()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_fake_test.go:90 +0x91
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163
==================
--- FAIL: TestMock_Sleep (0.00s)
    testing.go:809: race detected during execution of test
==================
WARNING: DATA RACE
Read at 0x00c0000884e8 by goroutine 29:
  github.com/leononame/clock.TestClock_AfterFunc()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_real_test.go:88 +0x12e
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163

Previous write at 0x00c0000884e8 by goroutine 30:
  sync/atomic.AddInt32()
      /usr/lib/go/src/runtime/race_amd64.s:269 +0xb
  github.com/leononame/clock.TestClock_AfterFunc.func1()
      /home/jake/go/pkg/mod/github.com/leononame/clock@v0.1.5/clock_real_test.go:86 +0x49

Goroutine 29 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:138 +0x334

Goroutine 30 (finished) created at:
  time.goFunc()
      /usr/lib/go/src/time/sleep.go:169 +0x51
==================
--- FAIL: TestClock_AfterFunc (0.04s)
    testing.go:809: race detected during execution of test
--- FAIL: TestMock_Sleep (0.00s)
    clock_fake_test.go:101: 
        	Error Trace:	clock_fake_test.go:101
        	Error:      	Should not be zero, but was 0
        	Test:       	TestMock_Sleep
--- FAIL: TestMock_Sleep (0.00s)
    clock_fake_test.go:101: 
        	Error Trace:	clock_fake_test.go:101
        	Error:      	Should not be zero, but was 0
        	Test:       	TestMock_Sleep
--- FAIL: TestMock_Sleep (0.00s)
    clock_fake_test.go:101: 
        	Error Trace:	clock_fake_test.go:101
        	Error:      	Should not be zero, but was 0
        	Test:       	TestMock_Sleep
--- FAIL: TestMock_Sleep (0.00s)
    clock_fake_test.go:101: 
        	Error Trace:	clock_fake_test.go:101
        	Error:      	Should not be zero, but was 0
        	Test:       	TestMock_Sleep
--- FAIL: TestMock_Sleep (0.00s)
    clock_fake_test.go:101: 
        	Error Trace:	clock_fake_test.go:101
        	Error:      	Should not be zero, but was 0
        	Test:       	TestMock_Sleep
--- FAIL: TestFakeTicker_Stop (0.04s)
    ticker_test.go:65: 
        	Error Trace:	ticker_test.go:65
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestFakeTicker_Stop
--- FAIL: TestFakeTimer_Stop (0.00s)
    timer_test.go:54: 
        	Error Trace:	timer_test.go:54
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestFakeTimer_Stop
FAIL
coverage: 97.9% of statements
FAIL	github.com/leononame/clock	6.350s

</details>

The races match what I see when using the library as well, and I also have trouble with things sometimes not firing (when doing tests that increment a number, similarly to the tests in this repo).

**Comment by leononame** [comment]
Hi,

Thanks for your feedback. I'm currently travelling, but look at it next week to figure out where exactly the race condition originates from. 

Leo

**Comment by leononame** [comment]
Alright, I found the issues. Two tests had errors in them, plus a race condition the Mock. I hope this helps you and thanks for submitting the issue!

Leo
